// Generated by tool/GenerateData

export type SinglePetData = {
	name: string,
	idleSprites: string[],
	moveSprites: string[],
	thumbnailSprite: string,
	activeLevel: number,
	idleFrameLengthMs: number,
	moveFrameLengthMs: number,
	moveSpeed: number,
}

export const petData: { [petName: string]: SinglePetData } = {
	testPet: {
		name: "Test Pet",
		idleSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/test_pet/idle/Test_Pet_Idle_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/test_pet/idle/Test_Pet_Idle_2.png"),
		],
		moveSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/test_pet/move/Test_Pet_Move_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/test_pet/move/Test_Pet_Move_2.png"),
		],
		thumbnailSprite: 			browser.runtime.getURL("/sprites/pet_sprites/test_pet/idle/Test_Pet_Idle_1.png"),
		activeLevel: 5,
		idleFrameLengthMs: 1000,
		moveFrameLengthMs: 1000,
		moveSpeed: 20,
	},
	slime: {
		name: "The Witch's Slime",
		idleSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/slime/idle/Slime_Idle_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/slime/idle/Slime_Idle_2.png"),
		],
		moveSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/slime/move/Slime_Move_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/slime/move/Slime_Move_2.png"),
		],
		thumbnailSprite: 			browser.runtime.getURL("/sprites/pet_sprites/slime/idle/Slime_Idle_2.png"),
		activeLevel: 3,
		idleFrameLengthMs: 1000,
		moveFrameLengthMs: 1000,
		moveSpeed: 20,
	},
	snowFox: {
		name: "Crystal Fox",
		idleSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/snow_fox/idle/Snow_Fox_Idle_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/snow_fox/idle/Snow_Fox_Idle_2.png"),
		],
		moveSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/snow_fox/move/Snow_Fox_Move_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/snow_fox/move/Snow_Fox_Move_2.png"),
			browser.runtime.getURL("/sprites/pet_sprites/snow_fox/move/Snow_Fox_Move_3.png"),
			browser.runtime.getURL("/sprites/pet_sprites/snow_fox/move/Snow_Fox_Move_4.png"),
		],
		thumbnailSprite: 			browser.runtime.getURL("/sprites/pet_sprites/snow_fox/idle/Snow_Fox_Idle_1.png"),
		activeLevel: 2,
		idleFrameLengthMs: 3000,
		moveFrameLengthMs: 500,
		moveSpeed: 20,
	},
	armillaryRings: {
		name: "Armillary Rings",
		idleSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/idle/Armillary_Rings_Idle_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/idle/Armillary_Rings_Idle_2.png"),
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/idle/Armillary_Rings_Idle_3.png"),
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/idle/Armillary_Rings_Idle_4.png"),
		],
		moveSprites: [
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/move/Armillary_Rings_Move_1.png"),
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/move/Armillary_Rings_Move_2.png"),
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/move/Armillary_Rings_Move_3.png"),
			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/move/Armillary_Rings_Move_4.png"),
		],
		thumbnailSprite: 			browser.runtime.getURL("/sprites/pet_sprites/armillary_rings/idle/Armillary_Rings_Idle_1.png"),
		activeLevel: 4,
		idleFrameLengthMs: 500,
		moveFrameLengthMs: 500,
		moveSpeed: 20,
	},
};
